### ISSUE TITLE
iOS 12/13 fail to parse kernel macho

### ISSUE THREAD

**Issue by sherrellbc** [dongyangwu/p-joker#2]
```
Traceback (most recent call last):
  File "p-joker.py", line 189, in <module>
    kernel = KernelMachO(kernel_f)
  File "/Users/user/workspace/ios/p-joker/kernel/kernel.py", line 62, in __init__
    self.load(self.macho_file)
  File "/Users/user/workspace/ios/p-joker/kernel/kernel.py", line 78, in load
    self.load_header(fh, 0, size)
  File "/Users/user/workspace/ios/p-joker/kernel/kernel.py", line 107, in load_header
    hdr = MachOHeader(self, fh, offset, size, magic, hdr, endian)
  File "/Users/user/workspace/ios/p-joker/kernel/kernel.py", line 264, in __init__
    self.load(fh)
  File "/Users/user/workspace/ios/p-joker/kernel/kernel.py", line 290, in load
    raise ValueError("Unknown load command: %d" % (cmd_load.cmd,))
ValueError: Unknown load command: 50
```

The tool has not been updated in a while, so I was not expecting it to work. Are there plans to support newer kernel caches?

**Comment by lilang-wu** [comment]
I'm sorry, this error is due to the header of iOS 12/13 kernelcache was changed, you can use joker(http://newosxbook.com/tools/jtool.html) instead.

**Comment by sherrellbc** [comment]
Sorry, I missed your response. I just got the email. I am particularly interested in the support this tools provides for finding IOKit external methods and inheritance. But, as mentioned, it fails immediately while parsing the kernel.

**Comment by lilang-wu** [comment]
Hi, I have patched this error, please try it again!

**Comment by sherrellbc** [comment]
@lilang-wu Thanks for looking into this so quickly! Indeed the script now correctly parses the kernel image without issue. However I'm not convinced it is working correctly.

The following invocation:
`python p-joker.py kernelcache.decrypted -e "['all']"`

Will report a lot to the console, but emits nothing to the current directory (or any directory specified by `-d`).

> <type 'list'>
> 0x21c4000 0xfffffff007824000L
> Extract: total 75 kernel base object modinit
> (1/200)-------com.apple.driver.AppleSPUSphere---------
> Extract: total 1 kernel base object modinit
> (1/200)-------com.apple.driver.AppleUSBAudio---------
> Extract: total 13 kernel base object modinit
> (1/200)-------com.apple.driver.AppleCS42L71Audio---------
> Extract: total 2 kernel base object modinit
> ...

However, the invocation that targets a particular kext _does_ emit a `MetaClass.txt` file to the specified directory, but otherwise behaves identically to the 'all' option as shown above.

`python p-joker.py kernelcache.decrypted -e "['com.apple.iokit.IOHIDFamily']"`

> <type 'list'>
> 0x21c4000 0xfffffff007824000L
> Extract: total 75 kernel base object modinit
> Extract: total 23 kernel base object modinit
> Extract: total 75 kernel base object modinit
> (1/200)-------com.apple.driver.AppleSPUSphere---------
> Extract: total 1 kernel base object modinit
> (2/200)-------com.apple.driver.AppleUSBAudio---------
> Extract: total 13 kernel base object modinit
> (3/200)-------com.apple.driver.AppleCS42L71Audio---------
> Extract: total 2 kernel base object modinit
> ...
> (72/200)-------com.apple.driver.AppleSPU---------
> Extract: total 32 kernel base object modinit
> Extract: find not reg according this name!
> Extract: find not reg according this name!
> Extract: find not reg according this name!
> Extract: find not reg according this name!
> ...
> (198/200)-------com.apple.driver.AppleBasebandPCI---------
> Extract: total 21 kernel base object modinit
> (199/200)-------com.apple.driver.AppleC26Charger---------
> Extract: total 4 kernel base object modinit
> (200/200)-------com.apple.driver.DiskImages.KernelBacked---------
> Extract: total 7 kernel base object modinit
> {}

`MetaClass.txt` looks like this:

> "AppleUSBCapabilityDescriptor",
> "IOBiometricUserClient",
> "AppleBCMWLANSkywalkRxCompletionQueue",
> "AppleBCMWLANNetManager",
> "IOPMrootDomain",
> "AppleUSBRequestPool",
> "AppleNullTextCrypter",
> "IO80211VirtualInterfaceNamer",
> "AppleBCMWLANPCIeSkywalkPacket",
> "IOUSBDeviceController",
> ...

I can look into it when I have the time. I think this tool has a lot of value.

**Comment by lilang-wu** [comment]
For p-joker -e feature, I have added the note in the usage. you should use this feature on Linux.
The capstone on macOS can't parse str instruction correctly. I will solve this error later. Besides, the -e feature does not support iOS 12/13 currently, I will also revise it later.

**Comment by sherrellbc** [comment]
I saw that note. I tried it on Linux and observed the same behavior. This ticket is closed since the kernel is properly parsed now. Though another should likely be opened for the iOS12/13 support for `-e`.

Thanks for taking the time to continue to support this tool.

**Comment by lilang-wu** [comment]
p-joker.py now can support iOS 12/13 now. you can directly use it on MacOS.

**Comment by sherrellbc** [comment]
Confirmed OSX works great. I've not dug into it myself,  but it seems to be working at runtime. Although there is no output. On an iphone7 13.3.1 kernel:

```
$ python p-joker.py kernel -e "['all']" -d tmp/
[+] prepare string table
[+] prepare some critical offsets
[+] check if the kernelcache contains PAC info
[+] prepare the region range of (__TEXT_EXEC, __text) section for each kernel extension
[+] prepare the region range of prelink sections for IOS 10/11
[+] setup OSMetaClass::OSMetaClass(char const*,OSMetaClass const*,uint) function address
[+] start analyze the meta classes within kernel
                [>] analysis_mif: total 75 kernel base object modinit
                [>] (1/74) analysis_mif: start to analyze init function 0xfffffff0075f1e68L ...
...
                [>] (74/74) analysis_mif: start to analyze init function 0xfffffff0076bb3b0L ...
[+] build the relationship for meta classes within kernel
[+] start analyze the meta classes within each kernel extensions
        [-] analysis_mif_kext: (1/200) analyzing kernel extensions com.apple.driver.AppleSPUSphere
                [>] analysis_mif: total 0 kernel base object modinit
        [-] analysis_mif_kext: (2/200) analyzing kernel extensions com.apple.driver.AppleUSBAudio
                [>] analysis_mif: total 0 kernel base object modinit
...
        [-] analysis_mif_kext: (199/200) analyzing kernel extensions com.apple.driver.DiskImages.KernelBacked
                [>] analysis_mif: total 0 kernel base object modinit
[+] build the relationship for meta classes
```

And the output directory is empty. The output is slightly different if I target a specific kext as shown in the usage:

```
$ python p-joker.py kernel -e "['com.apple.iokit.IOHIDFamily']" -d tmp/
[+] prepare string table
[+] prepare some critical offsets
[+] check if the kernelcache contains PAC info
[+] prepare the region range of (__TEXT_EXEC, __text) section for each kernel extension
[+] prepare the region range of prelink sections for IOS 10/11
[+] setup OSMetaClass::OSMetaClass(char const*,OSMetaClass const*,uint) function address
[+] start analyze the meta classes within kernel
                [>] analysis_mif: total 75 kernel base object modinit
                [>] (1/74) analysis_mif: start to analyze init function 0xfffffff0075f1e68L ...
...
                [>] (74/74) analysis_mif: start to analyze init function 0xfffffff0076bb3b0L ...
[+] build the relationship for meta classes within kernel
[+] start analyze the meta classes within each kernel extensions
0xfffffff00569bb00L 0x85bb00L
                [>] analysis_mif: total 0 kernel base object modinit
        [-] get_all_metaclass: total 75 kernel base object modinit
        [-] get_metaclass_v1: (1/200) get metaclasses from com.apple.driver.AppleSPUSphere ...
        [-] get_all_metaclass: total 1 kernel base object modinit
        [-] get_metaclass_v1: (2/200) get metaclasses from com.apple.driver.AppleUSBAudio ...
...
        [-] get_metaclass_v1: (200/200) get metaclasses from com.apple.driver.DiskImages.KernelBacked ...
        [-] get_all_metaclass: total 7 kernel base object modinit
[+] build the relationship for meta classes
```

In particular, most of the lines find a non-zero base object:
`total 75 kernel base object modinit`.

Though lots of useful information can be emitted if you set debug on [this](https://github.com/lilang-wu/p-joker/blob/master/iokit_kextclass/kext_analyzer.py#L1690) line (step `build the relationship for meta classes within kernel`). Still nothing emitted to the output directory, or on the last step (`build the relationship for meta classes`). Though the last step already had debug enabled.

**Comment by lilang-wu** [comment]
-e feature do not support -d option，just run python p-joker.py kernelcache -e “[‘driver_bundleid’]”, what’s more, do you install the newest capstone in the next brunch?

**Comment by sherrellbc** [comment]
I figured as much. Seems to be used only for decryption of the kernel. What capstone version are you using? I have:

`capstone            4.0.2`

**Comment by lilang-wu** [comment]
Please refer to the readme :)

**Comment by sherrellbc** [comment]
Ah. I did not see the new requirement. However, the output remains unchanged after the upgrade:

```
$ pip list
Package    Version
---------- -------
capstone   5.0.0
cxxfilt    0.2.1
pip        20.0.2
pylzfse    0.2
setuptools 44.1.0
wheel      0.34.2
```

Output:
```
$ python p-joker.py kernel -e "['all']"
[+] prepare string table
[+] prepare some critical offsets
[+] check if the kernelcache contains PAC info
[+] prepare the region range of (__TEXT_EXEC, __text) section for each kernel extension
[+] prepare the region range of prelink sections for IOS 10/11
[+] setup OSMetaClass::OSMetaClass(char const*,OSMetaClass const*,uint) function address
[+] start analyze the meta classes within kernel
                [>] analysis_mif: total 75 kernel base object modinit
                [>] (1/74) analysis_mif: start to analyze init function 0xfffffff0075f1e68L ...
...
                [>] (74/74) analysis_mif: start to analyze init function 0xfffffff0076bb3b0L ...
[+] build the relationship for meta classes within kernel
[+] start analyze the meta classes within each kernel extensions
        [-] analysis_mif_kext: (1/200) analyzing kernel extensions com.apple.driver.AppleSPUSphere
                [>] analysis_mif: total 0 kernel base object modinit
...
        [-] analysis_mif_kext: (199/200) analyzing kernel extensions com.apple.driver.DiskImages.KernelBacked
                [>] analysis_mif: total 0 kernel base object modinit
[+] build the relationship for meta classes
```

**Comment by lilang-wu** [comment]
You can give me the Ipsw download link, i wii test for you tomorrow

**Comment by sherrellbc** [comment]
Just 13.3.1 on the iPhone7 (d10ap). [Link](https://updates.cdn-apple.com/2020WinterFCS/fullrestores/061-40875/1E51B88F-53F7-40AB-9E40-E72F1E35D8E3/iPhone_4.7_P3_13.3.1_17D50_Restore.ipsw).

Anyway, thanks for the quick responses here.

**Comment by lilang-wu** [comment]
Or you can try the iOS 13 for iPhone 11

**Comment by sherrellbc** [comment]
Quite different. I think that does work, though the iphone7 must not then. [Here is the output](https://github.com/lilang-wu/p-joker/files/4622621/out.txt). Both were 13.3.1 kernels.

**Comment by lilang-wu** [comment]
I did not test for all phone model, and will test iPhone 7 tomorrow

**Comment by sherrellbc** [comment]
The iphone7 is just often simpler, since it has only two cores. Thanks for your time looking into this and working on the updates.
